package daemon

func capabilities() map[string]any {
	return map[string]any{
		"protocol": 1,
		"events":   []string{"state", "viz", "job", "warm"},
		"methods": []map[string]any{
			{"name": "capabilities", "params": nil},
			{"name": "state.get", "params": nil},
			{"name": "subscribe", "params": nil},
			{"name": "spectrum.get", "params": nil},
			{"name": "playback.toggle", "params": nil},
			{"name": "playback.next", "params": nil},
			{"name": "playback.prev", "params": nil},
			{"name": "playback.stop", "params": nil},
			{"name": "playback.seek", "params": map[string]string{"seconds": "number"}},
			{"name": "playback.volume.set", "params": map[string]string{"volume": "int"}},
			{"name": "playback.volume.delta", "params": map[string]string{"delta": "int"}},
			{"name": "playback.shuffle", "params": map[string]string{"on": "bool"}},
			{"name": "queue.replace", "params": map[string]string{"paths": "[]string", "start_path": "string", "if_revision": "uint64?"}},
			{"name": "queue.load", "params": map[string]string{"paths": "[]string", "start_path": "string", "if_revision": "uint64?"}},
			{"name": "queue.play_path", "params": map[string]string{"path": "string", "if_revision": "uint64?"}},
			{"name": "queue.play_current", "params": map[string]string{"paths": "[]string", "start_path": "string", "if_revision": "uint64?"}},
			{"name": "queue.append", "params": map[string]string{"paths": "[]string", "if_revision": "uint64?"}},
			{"name": "queue.move", "params": map[string]string{"index": "int", "delta": "int", "if_revision": "uint64?"}},
			{"name": "queue.append_folder", "params": map[string]string{"path": "string", "if_revision": "uint64?"}},
			{"name": "queue.up_next", "params": map[string]string{"limit": "int"}},
			{"name": "viz.subscribe", "params": nil},
			{"name": "viz.unsubscribe", "params": nil},
			{"name": "viz.config", "params": nil},
			{"name": "viz.config.apply", "params": nil},
			{"name": "viz.config.set", "params": map[string]string{"frame_rate": "int", "sensitivity": "int"}},
			{"name": "config.set", "params": map[string]string{"section": "string", "key": "string", "value": "string"}},
			{"name": "library.meta", "params": map[string]string{"path": "string"}},
			{"name": "library.browse", "params": map[string]string{"path": "string"}},
			{"name": "library.warm", "params": map[string]string{"path": "string"}},
			{"name": "library.warm.batch", "params": map[string]string{"paths": "[]string", "workers": "int", "art": "bool"}},
			{"name": "library.warm.waveform", "params": map[string]string{"path": "string"}},
			{"name": "library.genres", "params": nil},
			{"name": "library.tracks", "params": map[string]string{"genre": "string"}},
			{"name": "library.search", "params": map[string]string{"mode": "string", "query": "string"}},
			{"name": "library.incoming.list", "params": nil},
			{"name": "library.incoming.set_genre", "params": map[string]string{"path": "string", "genre": "string", "folder": "string"}},
			{"name": "library.playlist.list", "params": nil},
			{"name": "library.playlist.tracks", "params": map[string]string{"name": "string", "offset": "int", "limit": "int"}},
			{"name": "library.playlist.star", "params": map[string]string{"name": "string"}},
			{"name": "library.favorite.toggle", "params": map[string]string{"path": "string"}},
			{"name": "library.track.move", "params": map[string]string{"path": "string", "folder": "string"}},
			{"name": "library.track.tags.get", "params": map[string]string{"path": "string"}},
			{"name": "library.track.tags.set", "params": map[string]string{"path": "string", "title": "string", "artist": "string", "year": "string", "genre": "string", "label": "string"}},
			{"name": "library.current.load", "params": nil},
			{"name": "library.current.save", "params": map[string]string{"paths": "[]string"}},
			{"name": "library.import", "params": nil},
			{"name": "library.cache", "params": map[string]string{"genre": "string", "force": "bool"}},
			{"name": "library.soundcloud.download", "params": map[string]string{"import": "bool"}},
			{"name": "library.download", "params": map[string]string{"url": "string", "import": "bool?"}},
			{"name": "library.art.maintain", "params": nil},
			{"name": "scrobble.nowplaying", "params": nil},
			{"name": "scrobble.submit", "params": map[string]string{"started": "int"}},
			{"name": "job.status", "params": nil},
			{"name": "job.cancel", "params": nil},
		},
		"error_codes": []string{
			"invalid_params",
			"conflict",
			"not_found",
			"unavailable",
			"unknown_method",
		},
	}
}
