package daemon

func capabilities() map[string]any {
	return map[string]any{
		"protocol": 1,
		"events":   []string{"state", "viz", "job", "warm"},
		"methods": []map[string]any{
			{"name": "capabilities", "params": nil},
			{"name": "state.get", "params": nil},
			{"name": "subscribe", "params": nil},
			{"name": "spectrum.get", "params": nil},
			{"name": "playback.toggle", "params": nil},
			{"name": "playback.next", "params": nil},
			{"name": "playback.prev", "params": nil},
			{"name": "playback.stop", "params": nil},
			{"name": "playback.seek", "params": map[string]string{"seconds": "number"}},
			{"name": "playback.volume.set", "params": map[string]string{"volume": "int"}},
			{"name": "playback.volume.delta", "params": map[string]string{"delta": "int"}},
			{"name": "playback.shuffle", "params": map[string]string{"on": "bool"}},
			{"name": "queue.replace", "params": map[string]string{"paths": "[]string", "start_path": "string", "if_revision": "uint64?"}},
			{"name": "queue.load", "params": map[string]string{"paths": "[]string", "start_path": "string", "if_revision": "uint64?"}},
			{"name": "queue.play_path", "params": map[string]string{"path": "string", "if_revision": "uint64?"}},
			{"name": "queue.play_current", "params": map[string]string{"paths": "[]string", "start_path": "string", "if_revision": "uint64?"}},
			{"name": "queue.append", "params": map[string]string{"paths": "[]string", "if_revision": "uint64?"}},
			{"name": "queue.append_folder", "params": map[string]string{"path": "string", "if_revision": "uint64?"}},
			{"name": "queue.up_next", "params": map[string]string{"limit": "int"}},
			{"name": "viz.subscribe", "params": nil},
			{"name": "viz.unsubscribe", "params": nil},
			{"name": "viz.config", "params": nil},
			{"name": "viz.config.apply", "params": nil},
			{"name": "viz.config.set", "params": map[string]string{"frame_rate": "int", "sensitivity": "int"}},
			{"name": "library.meta", "params": map[string]string{"path": "string"}},
			{"name": "library.browse", "params": map[string]string{"path": "string"}},
			{"name": "library.warm", "params": map[string]string{"path": "string"}},
			{"name": "library.warm.batch", "params": map[string]string{"paths": "[]string", "workers": "int", "art": "bool"}},
			{"name": "library.warm.waveform", "params": map[string]string{"path": "string"}},
			{"name": "scrobble.nowplaying", "params": nil},
			{"name": "scrobble.submit", "params": map[string]string{"started": "int"}},
			{"name": "job.status", "params": nil},
			{"name": "job.cancel", "params": nil},
		},
		"error_codes": []string{
			"invalid_params",
			"conflict",
			"not_found",
			"unavailable",
			"unknown_method",
		},
	}
}
